version: '3'
services:
  db:
    image: postgres:12
    volumes:
      - music_postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres

  web:
    image: song-test-api:latest
    volumes:
      - .:/app
    ports:
      - mode: host
        target: 127.0.0.1:3001
        published: 3000
    depends_on:
      - db
    environment:
      RACK_ENV: production

volumes:
  music_postgres:
    driver: local
